project:
  type: website



website:
  title: ""
  page-footer:
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/Collaborative-RStudio-GitHub
  repo-actions: [edit, issue]
  page-navigation: true
  favicon: assets/LMU-OSC_favicon.jpg
  margin-header: |
  ![](/assets/LMU-OSC_logo.jpg){width="175"}
  navbar:
    left:
      - href: index.md

  sidebar:
    style: docked
    contents:
      - text: "Home"
        href: index.md
      - section: "Tutorial"
        contents:
          - href: fork.md
            text: "Fork a Repo"
          - href: clone.md
            text: "Clone a Repo"
          - href: commit.md
            text: "Commit to a Project"
          - href: push.md
            text: "Push Changes"
          - href: pull-request.md
            text: "Pull Request"
          - href: merge.md
            text: "Merge Changes"
          - href: pull-upstream.md
            text: "Pull Upstream"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



